version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    #run command in shell using sh -c
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"